services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    command: sh -c "uvicorn portal.asgi:application --host 0.0.0.0 --port 8001 --reload --ssl-keyfile ${SSL_KEYFILE} --ssl-certfile ${SSL_CERTFILE}"
    volumes:
      - .:/home/portal
      - staticfiles:/home/portal/staticfiles
    env_file:
      - .env
    depends_on:
      - palette_db
      - redis
      - rabbitmq
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=${DB_PASSWORD} pg_isready -U ${DB_USER} -d ${DB_NAME} -h ${DB_HOST} -p ${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A portal worker -l info
    volumes:
      - .:/home/portal
    env_file:
      - .env
    depends_on:
      - palette_db
      - redis
      - rabbitmq
    restart: always

  beat:
    container_name: beat
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A portal beat -l info
    volumes:
      - .:/home/portal
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  palette_db:
    container_name: palette_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - redis_data:/home/portal/redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    env_file:
      - .env
    ports:
      - 5672:5672 # RabbitMQ Server port
      - 15672:15672 # RabbitMQ management UI port
    restart: always

volumes:
  postgres_data:
  staticfiles:
  redis_data: