# Run with `docker-compose up [-d] --build`
services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && uvicorn portal.asgi:application --host 0.0.0.0 --port 8001 --reload"
    volumes:
      - .:/home/portal
      - staticfiles:/home/portal/staticfiles
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  staticfiles:
