services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && uvicorn portal.asgi:application --host 0.0.0.0 --port 8001 --reload"
    volumes:
      - .:/home/portal
      - staticfiles:/home/portal/staticfiles
    env_file:
      - .env
    depends_on:
      - palette_db
      - redis
      - session_redis
      - chat_redis

    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=${DB_PASSWORD} pg_isready -U ${DB_USER} -d ${DB_NAME} -h ${DB_HOST} -p ${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  palette_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  session_redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - "6380:6379"
    command: ["redis-server", "--port", "6379", "--requirepass", "${REDIS_PASSWORD}"]

  chat_redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - "6381:6379"
    command: ["redis-server", "--port", "6379", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  postgres_data:
  staticfiles:
